membrane/api-gateway

- cli/examples/groovy/proxies.xml
- cli/src/test/java/com/predic8/membrane/examples/tests/GroovyTest.java
- core/pom.xml
- core/src/main/java/com/predic8/membrane/core/interceptor/groovy/GroovyInterceptor.java
- core/src/test/java/com/predic8/membrane/core/interceptor/groovy/GroovyInterceptorTest.java
- pom.xml
- test/pom.xml
example :
<spring:bean name="mySpringBean" class="java.lang.String">
<spring:constructor-arg value="Groovy interceptor"/>
</spring:bean>
<router>
<serviceProxy port="2000">
<request>
<groovy>
def value = spring.getBean("mySpringBean")
exc.request.header.add("X-Groovy", value)
println "X-Groovy header added with value :" + value
CONTINUE
</groovy>
</request>
</serviceProxy>
</router>
> New feature : access to spring application context from groovy interceptor

- core/src/main/resources/com/predic8/membrane/core/interceptor/rest/xml2json.xsl
bad generation of json when the xml contains values as (007, 04 ...), are considered as Number and miss the double quote.
> Avoid considering value that start with 0 as Number (ex. 003)

- core/src/main/java/com/predic8/membrane/core/interceptor/Interceptor.java
- core/src/test/java/com/predic8/membrane/core/interceptor/balancer/LoadBalancingWithClusterManagerTest.java
- core/src/test/java/com/predic8/membrane/core/services/DummyWebServiceInterceptor.java
- core/src/test/java/com/predic8/membrane/interceptor/LoadBalancingInterceptorTest.java
- core/src/test/java/com/predic8/membrane/interceptor/MultipleLoadBalancersTest.java
Note: this class is only used by tests, therefore that's not a critical issue.
Currently there are no tests using multi-threading. In my own tests (contributions will follow) firing 100 requests, the volatile counter consistently got to 96-97 because the ++ operation is not atomic.
> Made DummyWebServiceInterceptor thread safe. 

- core/src/main/java/com/predic8/membrane/core/interceptor/balancer/LoadBalancingInterceptor.java
as suggested by Thomas Bayer on the mailing list https://mail.google.com/mail/u/0/#inbox/146db8f4a04962ee
> LoadBalancingInterceptor: added missing call to DispatchingStrategy.done()

- core/src/main/java/com/predic8/membrane/core/RouterCLI.java
- core/src/main/java/com/predic8/membrane/core/transport/http/StreamPump.java
- core/src/test/java/com/predic8/membrane/core/interceptor/xmlprotection/XMLProtectorTest.java
- core/src/test/java/com/predic8/membrane/core/util/DNSCacheTest.java
- war/src/main/java/com/predic8/membrane/servlet/embedded/HttpServletHandler.java
- war/src/test/java/com/predic8/membrane/servlet/test/ResolverTestTriggerTest.java
Simple patch which removes a few warning about usage exception.printStackTrace().
> exception.printStackTrace() was replaced with LOG.error(...)

- core/src/main/java/com/predic8/membrane/core/interceptor/schemavalidation/ValidatorInterceptor.java
By wrapping the validation action with try-catch and AbortException, it prevents membrane from quitting unexpectedly when the underlying validation code fails and throws validation exception incorrectly inherited from IOException, such as the default Jackson JSON validator framework.
Because Jackson's JSONParseException inherits IOException, membrane will simply disconnect when the parser failed, e.g. upon any invalid JSON format, and resulted in membrane uncaught exception and unexpected response result.
> wrap any validation error with AbortException.

- README.md
This PR adds two badges
* one to display and link to the latest release (the link is updated automatically when a new release is made)
[![GitHub release](https://img.shields.io/github/release/membrane/service-proxy.svg)](https://github.com/membrane/service-proxy/releases/latest)
* one to display and link to the project's license
[![Hex.pm](https://img.shields.io/hexpm/l/plug.svg)](https://raw.githubusercontent.com/membrane/service-proxy/master/distribution/router/CHANGELOG.txt)
> Add release and license badges

- core/src/main/java/com/predic8/membrane/core/interceptor/server/WebServerInterceptor.java
Catch Block catches FileNotFoundException while in reality, it's already wrapped into a ResourceRetrievalException, which causes this catch clause to miss, allowing the Exception to travel up the entire stack and being printed on the STDOUT.
> Fixing catchblock catching wrong exception

- distribution/examples/embedding-java/pom.xml
- pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

- core/src/main/java/com/predic8/membrane/core/transport/http/Connection.java
I found an obvious bug in Connection.doTunnelHandshake: it sends HTTP/1.**0** request and waits for HTTP/1.**1** response. It's very strange behavior. It doesn't work for me.
Moreover Connection.doTunnelHandshake is a clean copy of https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/samples/sockets/client/SSLSocketClientWithTunneling.java except only this string.
I've change this line, but HTTP/1.**1** is left too because it was made for some reason, and [some people int the internet complained](https://community.oracle.com/thread/1535854) some HTTP proxies returned HTTP/1.1 response for HTTP/1.0 request
> proxy should work with HTTP/1.0 too

- core/src/test/java/com/predic8/membrane/core/cloud/etcd/EtcdRequestTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/apimanagement/AMQuotaInterceptorTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/apimanagement/AMRateLimitInterceptorTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/apimanagement/ApiManagementConfigurationTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/apimanagement/ApiManagementInterceptorTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/OAuth2AuthorizationServerInterceptorBase.java
I could not executed the tests under linux because we don't have backslashes in our path.
I basically only replaced the escaped backslashes with slashes in the tests to allow for tests to run under linux properly.
> Replacing \\ with / in Unit Tests.

- core/src/main/java/com/predic8/membrane/core/interceptor/rewrite/RewriteInterceptor.java
Extracting host/port using double-slash instead of comparing the pathQuery with URL as the pathQuery could be decoded, which doesn't match the original URL and resulted in null schemaHost.
> Fix the host:port extraction algorithm bug causing the <rewrite> tag failure

- core/src/main/java/com/predic8/membrane/core/interceptor/WADLInterceptor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/WSDLInterceptor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/rewrite/ReverseProxyingInterceptor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/soap/WebServiceExplorerInterceptor.java
- core/src/main/java/com/predic8/membrane/core/ws/relocator/Relocator.java
- core/src/test/java/com/predic8/membrane/core/ws/relocator/RelocatorTest.java
- core/src/test/java/com/predic8/membrane/core/ws/relocator/RelocatorWADLTest.java
soapProxy now works with different context paths (tested for war deployment)
> issue #59: Context path missing from WSDL endpoint

- core/src/main/java/com/predic8/membrane/core/rules/SwaggerProxyKey.java
Problem:
In some paths, there are query parameters (e.g. GET-/pet/findByStatus in http://petstore.swagger.io/v2/swagger.json). The method "pathTemplateMatch" doesn't remove those parameters and returns false so the RuleManager cannot found a rule. The system gives "Bad Request" errors.
Solution:
The query parameters are removed before calling the Pattern.matches method.
> remove query parameters from calledURI

- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2client/RedisOriginalExchangeStore.java
- distribution/src/main/java/com/predic8/membrane/core/IDEStarter.java
Expiring the Redis keys after 1 hour to prevent stacking originalRequests in Redis when the authorization process fails or is cancelled.
> changed RedisOriginalExchangestore to expire keys

- .run/IDEStarter.run.xml
Adjust IDE Starter configuration to match renamed module "membrane-service-proxy"
> Adjust IDE Starter configuration to renamed module

- core/src/test/java/com/predic8/membrane/core/interceptor/templating/TemplateInterceptorTest.java
Paths.get() uses system path separator between arguments
> Paths.get() handles path separator

- core/src/test/java/com/predic8/membrane/core/util/FileUtilTest.java
Test attempted to create a temp file at "/tmptest.tmp", resulting in a permission error. Added path separator to temp file path
> Fix permission error in FileUtilTest

- core/src/main/java/com/predic8/membrane/core/interceptor/apimanagement/ApiManagementConfiguration.java
- core/src/main/java/com/predic8/membrane/core/interceptor/jwt/Jwks.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/ConsentPageFile.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/authorizationservice/MembraneAuthorizationService.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/parameter/ClaimsParameter.java
- core/src/test/java/com/predic8/membrane/core/interceptor/session/SessionInterceptorTest.java
Pass TypeReference to ObjectMapper.readValue to preserve Map type parameters
> Reduce number of unchecked cast warnings when parsing JSON/YAML data

- distribution/src/test/java/com/predic8/membrane/examples/util/Process2.java
if it works as expected, Process2 can be significantly simplified afterwards (startCommand)
> recursively kill all children of spawned process instead of shell magic

- core/src/main/java/com/predic8/membrane/core/interceptor/authentication/session/FileUserDataProvider.java
- distribution/examples/basic-auth/.htpasswd
- distribution/examples/basic-auth/README.md
- distribution/examples/basic-auth/proxies.xml
Added a UserDataProvider compatible with htpasswd formatted files.
Added the the provider to the basic-auth example next to the StaticUserDataProvider example.
> Added fileUserDataProvider & integration into basic-auth example

- core/src/main/resources/com/predic8/membrane/core/interceptor/administration/docBase/admin/js/membrane.js
loadText() method got corrupted because of a method deprecation in jQuery.
This replaces the missing functions and properties.
-> This was causing problems like the request/response bodies not showing up in the call detail screen.
> Replaced deprecated navigator/browser version detection

- core/src/main/java/com/predic8/membrane/core/interceptor/grease/GreaseInterceptor.java
- core/src/test/java/com/predic8/membrane/core/interceptor/grease/GreaseInterceptorTest.java
Changed setter type of GreaseInterceptor.setRate() from Double to String, whereas the String gets parsed as double internally
> Changed setter type of GreaseInterceptor.setRate() from Double to String

- core/src/main/java/com/predic8/membrane/core/openapi/serviceproxy/APIProxyKey.java
Switch to Java's Objects.equals() for a reliable null safe equals check.
This caused ACME http challenge to fail because it relied on the equals check!
> Fix testExpression being null breaking APIProxyKey equals method

- core/src/main/java/com/predic8/membrane/core/openapi/util/Utils.java
Membrane did not start when packaged in jar: 
```sh
Membrane Router running...
16:09:03,482  INFO 1 main OpenAPIRecordFactory:83 - Parsing spec fruitshop-api.yml
org.springframework.context.ApplicationContextException: Failed to start bean 'router'
at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:288)
at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:472)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:257)
at org.springframework.context.support.DefaultLifecycleProcessor.start(DefaultLifecycleProcessor.java:170)
at …
```
> Fixed getResourceAsStream 

- core/src/main/java/com/predic8/membrane/core/http/Response.java
- core/src/test/java/com/predic8/membrane/core/http/ResponseBuilderTest.java
I have added the body("") into bodyEmpty method.
I can also replace other existing body("") calls on a Response.redirect builder with new bodyEmpty method in another pull request if you want to consolidate the usage.
> Fix issue #1349 by setting body to empty string after 0 content-length.

- core/src/main/java/com/predic8/membrane/core/interceptor/xmlprotection/XMLProtectionException.java
- core/src/main/java/com/predic8/membrane/core/interceptor/xmlprotection/XMLProtector.java
- core/src/test/java/com/predic8/membrane/core/interceptor/xmlprotection/XMLProtectionInterceptorTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/xmlprotection/XMLProtectorTest.java
Before the DTD was just removed, now the request is blocked.
> Added check and block for external entity references in XMLProtection 

- core/src/main/java/com/predic8/membrane/core/transport/http/ConnectionManager.java
Hello,
We have experienced 502 - Bad Gateway errors on predic8 api-gateway. While I was searching for the root cause of SocketExceptions and HTTP 502 responses, I came to conclusion of this:
The api-gateway is reusing an old connection but it is not aware if this connection still exists. We found out this behaviour from TCP captures. Before the SocketException occurs, we have proofs that the entity behind the api gateway sends a RST package. First attempt after this RST package, the api gateway throws a SocketException. Because it is not aware that the connection is ended. After investigating TCP captures and the code, I found out the ConnectionManager does not check if the connection still valid before returning an existing connection. It just checks if the deathTime is reached. 
I …
> Fixing Socket Exception

- core/pom.xml
Maven seems to have a problem resolving the dependency (which is a `pom` only dependency, see https://repo1.maven.org/maven2/org/graalvm/js/js/24.1.2/ ) : https://github.com/membrane/api-gateway/actions/runs/13614966836/job/38056845671
> switch org.graalvm.js:js dependency to type 'pom'

- core/pom.xml
Fixing CVE by updating transitive dependency explicitly for issue #1725.
> Fixing CVE-2024-57699 for json-smart by updating it explicitly.
