membrane/api-gateway

- core/src/main/java/com/predic8/membrane/core/util/URLUtil.java
> Fixes #187

- core/src/main/java/com/predic8/membrane/core/transport/http/HttpClient.java
In such cases the extra call is totally worth it.
> Only spend time creating debug log message if debug logging is enabled

- .gitignore
Simple change which adds files generated during tests and VIM-editor swap files to .gitignore.
> .gitignore for generated files and VIM swap

- core/src/main/java/com/predic8/membrane/core/interceptor/xslt/XSLTTransformer.java
- core/src/main/resources/com/predic8/membrane/core/interceptor/rest/xml2json.xsl
- distribution/pom.xml
xml2sjon update.
Updated the xml2json.xsl to the xsl from https://github.com/bramstein/xsltjson/ which has more functionality. Because it uses xsl 2.0 i had to use the saxon transformer instead of the default one. Saxon also seems to be faster.
> Xml2json update

- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/processors/DefaultEndpointProcessor.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/AuthWithSessionRequestTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/AuthWithoutSessionOpenidRequestTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/AuthWithoutSessionRequestTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/EmptyEndpointOpenidTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/EmptyEndpointTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/OAuth2AuthorizationServerInterceptorNormalTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/OAuth2AuthorizationServerInterceptorOpenidTest.java
Pull request for fixing unit tests. 
Previous branch with wrong fix is removed.
> Fix #323 by repairing unit tests to expect http status code 307 instead of 303.

- core/src/main/java/com/predic8/membrane/core/interceptor/templating/TemplateInterceptor.java
> Prettify JSON output

- core/src/main/java/com/predic8/membrane/core/interceptor/templating/TemplateInterceptor.java
> Show Template in Admin Console

- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2client/RedisOriginalExchangeStore.java
- core/src/main/java/com/predic8/membrane/core/interceptor/session/RedisSessionManager.java
- core/src/main/java/com/predic8/membrane/core/util/RedisConnector.java
to allow specifying multiple Redis host names
> switched from JedisPool to JedisCluster

- core/pom.xml
- distribution/pom.xml
- distribution/src/assembly/distribution.xml
- pom.xml
(see also https://github.com/CycloneDX/cyclonedx-maven-plugin )
> added cyclonedx maven plugin to generate bom, include bom in distribution

- core/src/main/java/com/predic8/membrane/core/exceptions/SpringConfigurationErrorHandler.java
Fixed two typos and did some refactoring to build error messages in a more functional style
> Error messages

- distribution/src/test/java/com/predic8/membrane/examples/util/Process2.java
Enable integration tests to kill Membrane process directly, removing the dependency on setsid on MacOS and preventing issues with kill command cascading to execution environment on some Linux distros
> kill Membrane process directly

- distribution/examples/basic-auth/README.md
Adjusted tabs and formulation of description / trimmed description.
> After-Review fixups for basic-auth example.

- distribution/src/test/java/com/predic8/membrane/examples/env/AntInPath.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/AddSoapHeaderTest.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/BasicXmlInterceptorTest.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/CustomInterceptorTest.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/QuickstartRESTTest.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/QuickstartSOAPTest.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/StaxExampleInterceptorTest.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/loadbalancing/BalancerClientScriptUtil.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/loadbalancing/Loadbalancing4XmlSessionTest.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/versioning/RoutingTest.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/versioning/XsltExampleTest.java
- distribution/src/test/java/com/predic8/membrane/examples/util/Process2.java
- distribution/src/test/java/com/predic8/membrane/examples/util/ProxiesXmlUtil.java
- distribution/src/test/java/com/predic8/membrane/examples/util/WaitableConsoleEvent.java
* Start Process directly instead of creating shell script
* terminate started process if watcher for startup message times out
* Refactoring
> Process2 hardening

- distribution/examples/acl/README.md
- distribution/examples/basic-auth/README.md
- distribution/examples/basic-xml-interceptor/README.md
- distribution/examples/custom-interceptor/README.md
- distribution/examples/groovy/README.md
- distribution/examples/internalproxy/README.md
- distribution/examples/javascript/README.md
- distribution/examples/loadbalancing/3-client/README.md
- distribution/examples/logging/console/README.md
- distribution/examples/message-transformation/json2xml/README.md
- distribution/examples/message-transformation/xml2json/README.md
- distribution/examples/openapi/README.md
- distribution/examples/openapi/openapi-proxy/README.md
- distribution/examples/openapi/validation-simple/README.md
- distribution/examples/openapi/validation/README.md
- distribution/examples/rateLimiter/README.md
- distribution/examples/rest2soap/README.md
- distribution/examples/rewriter/README.md
- distribution/examples/service-discovery-with-etcd/README.md
- distribution/examples/soap/add-soap-header/README.md
- distribution/examples/ssl/to-backend/README.md
- distribution/examples/stax-interceptor/README.md
- distribution/examples/stomp-over-websocket-intercepting/README.md
- distribution/examples/swagger-proxy/README.md
- distribution/examples/validation/soap-Proxy/README.md
- distribution/examples/versioning/routing/README.md
- distribution/examples/websocket-intercepting/README.md
- distribution/examples/websocket-stomp/README.md
- distribution/examples/xslt/README.md
- Examples now match with the proxies.xml
- replaced tabs with 2 spaces in example markdowns 
- corrected typos
> Example refactoring

- .github/workflows/docker-publish.yml
New pipeline file tested excluding Docker registry login, actual image push and signing
> Update Docker Release action

- .github/workflows/docker-publish.yml
- distribution/docker/Dockerfile
- distribution/docker/README.md
* add README for Docker Hub
* introduce Multiplatform build
> Dockerhub Improvements

- .github/workflows/docker-publish.yml
> use correct repository for docker hub credentials

- .github/workflows/maven-publish.yml
- annot/pom.xml
- core/.factorypath
- core/pom.xml
- distribution/examples/embedding-java/pom.xml
- distribution/examples/stax-interceptor/pom.xml
- distribution/pom.xml
- maven-plugin/pom.xml
- pom.xml
- starter/pom.xml
- test/pom.xml
- war/.factorypath
- war/pom.xml
run ConsistentVersionNumbers to avoid possible inconsistencies during Maven build and Maven Central upload
> snapshot release v5.1.11

- .github/workflows/release-build.yml
- .github/workflows/release-pr.yml
- distribution/release-notes/0.0.0.md
* triggered manually, enter desired version number in "Run workflow" dropdown
* creates PR
* triggers when PR with title starting with "Release " is merged
* creates PR for next snapshot version
* builds release ZIP file
* creates new Release with attached artifact, taking release notes from `distribution/release-notes/$VERSION.md`
> Release actions

- distribution/src/test/java/com/predic8/membrane/examples/env/ConsistentVersionNumbers.java
- membrane.spec
Update ConsistentVersionNumbers to handle RPM spec as well
> use CVN to keep RPM spec up to date

- distribution/src/test/java/com/predic8/membrane/examples/ExampleTestsWithoutInternet.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/JsonProtectionTest.java
Note: First test not working because:  #622
> implemented JsonProtectionTest

- core/src/main/java/com/predic8/membrane/core/interceptor/authentication/session/FileUserDataProvider.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/BasicAuthTest.java
- distribution/src/test/java/com/predic8/membrane/examples/tests/XSLTTest.java
Expanded basic-auth example test to incorporate new fileUserDataProvider
> Basic auth example test fileuserdataprovider

- distribution/examples/security/json-protection/service-proxy.bat
- distribution/examples/security/json-protection/service-proxy.sh
Fixed paths that have not been changed yet after move of json-protection example to security/json-protection
> Jsonprotection example starter paths

- distribution/examples/validation/form/README.md
- distribution/examples/validation/json-schema/README.md
- distribution/examples/validation/json-schema/proxies.xml
- distribution/examples/validation/soap-Proxy/README.md
- distribution/examples/validation/xml/README.md
- distribution/examples/validation/xml/proxies.xml
Rewrote/expanded/finished all validation examples.
> Validation example rewrite

- distribution/examples/throttle/README.md
- distribution/examples/throttle/proxies.xml
- distribution/examples/throttle/timing.bat
- distribution/examples/throttle/timing.sh
Rewrote example using curl request timing instead of telling the user to look at the website and "feel" if it's slower
> Throttle example rewrite

- distribution/examples/versioning/routing/README.md
- distribution/examples/versioning/routing/proxies.xml
- distribution/examples/versioning/xslt/README.md
Rewrote versioning sample readmes and tested them
> Versioning example rewrite

- core/src/main/java/com/predic8/membrane/core/interceptor/AbstractInterceptor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/Interceptor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/authentication/session/LoginInterceptor.java
- core/src/test/java/com/predic8/membrane/core/rules/ProxyRuleTest.java
- core/src/test/resources/ref.proxies.xml
Interceptor.id was not used besides one test and one interceptor, therefore it was removed
> Removed barely utilized interceptor.id

- DEVELOPING.md
- core/pom.xml
- distribution/pom.xml
- maven-plugin/pom.xml
- pom.xml
Added advanced reporting features to the maven site build goal.
- Added CVE vulnerability check
- Added dependency version check
> Advanced reporting

- core/src/main/java/com/predic8/membrane/core/DefaultConfig.java
- core/src/main/java/com/predic8/membrane/core/interceptor/authentication/xen/XenCredentialAccessor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/ConsentPageFile.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/OAuth2Util.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/request/ParameterizedRequest.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/request/UserinfoRequest.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/tokengenerators/BearerTokenGenerator.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2client/OAuth2PermissionCheckerInterceptor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/prometheus/PrometheusInterceptor.java
- core/src/main/java/com/predic8/membrane/core/lang/javascript/GraalVMJavascriptSupport.java
- core/src/main/java/com/predic8/membrane/core/lang/javascript/RhinoJavascriptLanguageSupport.java
- core/src/main/java/com/predic8/membrane/core/transport/http/HttpTransport.java
- core/src/main/java/com/predic8/membrane/core/ws/relocator/Relocator.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/OAuth2UtilTest.java
fixed keySet iteration and simplified, cleanup some code
> Sb performance group fix

- core/src/main/java/com/predic8/membrane/balancer/client/LBNotificationClient.java
- core/src/main/java/com/predic8/membrane/core/http/cookie/MessageBytes.java
- core/src/main/java/com/predic8/membrane/core/http/cookie/ServerCookie.java
- core/src/main/java/com/predic8/membrane/core/interceptor/apimanagement/apiconfig/EtcdRegistryApiConfig.java
- core/src/main/java/com/predic8/membrane/core/interceptor/balancer/ClusterNotificationInterceptor.java
removes comments which where open for discussion in #749
> remove prev comments

- distribution/examples/logging/access/README.md
- distribution/examples/logging/access/log4j2_access.xml
maybe rename log4j2_access.xml to log4j2.xml?
> added time to example

- distribution/examples/oauth2/api/README.md
[Merge Request for membrane-api.io](https://gitlab.com/predic8/core/membrane-api-io/-/merge_requests/9) has to be approved first.
> Added link to Postman tutorial on membrane-api.io

- .github/workflows/release-build.yml
Modified workflow to fix release action not creating tags within this repo
> Fix releases not associated with repository

- core/src/main/java/com/predic8/membrane/core/interceptor/misc/AbstractSetterInterceptor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/misc/SetHeaderInterceptor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/misc/SetPropertyInterceptor.java
- core/src/test/java/com/predic8/membrane/core/UnitTests.java
- core/src/test/java/com/predic8/membrane/core/interceptor/misc/SetHeaderInterceptorTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/misc/SetPropertyInterceptorTest.java
Added setProperty interceptor and generalized setHeader and setProperty interceptors
> setProperty Interceptor

- core/src/main/java/com/predic8/membrane/core/transport/ssl/acme/AcmeRenewal.java
adjust retry interval to something above 5/hour (see https://letsencrypt.org/docs/failed-validation-limit/ )
> adjust retry interval to something above 5/hour

- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/ReusableJsonGenerator.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/ReusableJsonGeneratorTest.java
Unit tests created to reprocude the issue.
jsonGenerator will be re-generated on reset call.
> Fix issue #1346 by re-generating the Json Generator on reset call.

- README.md
- core/src/main/java/com/predic8/membrane/core/interceptor/groovy/GroovyInterceptor.java
- core/src/main/java/com/predic8/membrane/core/lang/AbstractScriptInterceptor.java
- core/src/main/java/com/predic8/membrane/core/lang/ScriptingUtils.java
Return source and error in Problem Details descriptions. Added a hint for production setting.
> Scripting logging improvements

- distribution/examples/template/json/service-proxy.sh
- distribution/router/service-proxy.sh
> Fix Java version detection for Mac in service-proxy scripts

- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/BufferedJsonGenerator.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/OAuth2Util.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/WellknownFile.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/authorizationservice/DynamicRegistration.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/flows/TokenFlow.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/parameter/ClaimsParameter.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/processors/DefaultEndpointProcessor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/processors/EmptyEndpointProcessor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/processors/EndpointProcessor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/processors/RevocationEndpointProcessor.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/request/AuthWithSessionRequest.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/request/AuthWithoutSessionRequest.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/request/ParameterizedRequest.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/request/UserinfoRequest.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/request/tokenrequest/AuthorizationCodeFlow.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/request/tokenrequest/CredentialsFlow.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/request/tokenrequest/ErrorFlow.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/request/tokenrequest/PasswordFlow.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/request/tokenrequest/RefreshTokenFlow.java
- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/request/tokenrequest/TokenRequest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/BufferedJsonGeneratorTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/OAuth2TestUtil.java
> fix: make JsonGenerator not reusuable, as it is not thread safe and thereby error prone

- core/src/main/java/com/predic8/membrane/core/interceptor/oauth2client/rf/LogHelper.java
> fix: refactoring regression

- core/src/main/java/com/predic8/membrane/core/interceptor/authentication/session/totp/PasscodeGenerator.java
- core/src/main/java/com/predic8/membrane/core/interceptor/session/SessionManager.java
- core/src/main/java/com/predic8/membrane/core/transport/ssl/acme/AcmeKubernetesStorageEngine.java
- core/src/main/java/com/predic8/membrane/core/transport/ws/WebSocketFrame.java
- core/src/main/java/org/apache/http/impl/auth/NTLMEngineTrampoline.java
- core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/ClaimsParameterTest.java
- core/src/test/java/com/predic8/membrane/core/interceptor/xmlcontentfilter/XMLElementFinderTest.java
- core/src/test/java/com/predic8/membrane/evaluation/RequestPerformanceVersion1.java
- core/src/test/java/com/predic8/membrane/evaluation/RequestPerformanceVersion2.java
- core/src/test/java/com/predic8/membrane/evaluation/RequestPerformanceVersion3.java
- core/src/test/java/com/predic8/membrane/evaluation/RequestPerformanceVersion4.java
IntelliJ Code Inspections pointing to performance issues applied semi-automatically. Unit and Integrations tests still pass locally
> Intellij inspections performance

- .gitignore
- .run/IDEStarter.run.xml
- core/src/main/java/com/predic8/membrane/core/cli/CliCommand.java
- core/src/main/java/com/predic8/membrane/core/cli/RouterCLI.java
- Fix MembraneCLI bug with options having spaces in them
> - Add IDEStarter functional default config as IDEA run config in project
